// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import mock "github.com/stretchr/testify/mock"

import weather "github.com/juaguz/ml-test/app/models/weather"

// WeatherRepo is an autogenerated mock type for the WeatherRepo type
type WeatherRepo struct {
	mock.Mock
}

// Find provides a mock function with given fields: day
func (_m *WeatherRepo) Find(day int64) (weather.Weather, error) {
	ret := _m.Called(day)

	var r0 weather.Weather
	if rf, ok := ret.Get(0).(func(int64) weather.Weather); ok {
		r0 = rf(day)
	} else {
		r0 = ret.Get(0).(weather.Weather)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(day)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: _a0
func (_m *WeatherRepo) Store(_a0 *weather.Weather) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*weather.Weather) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
